<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <OpenHarmonyTarget>true</OpenHarmonyTarget>
    <OpenHarmonyApiLevel Condition="'$(OpenHarmonyApiLevel)' == ''">13</OpenHarmonyApiLevel>
    <OpenHarmonyAbi Condition="'$(OpenHarmonyAbi)' == ''">x86_64</OpenHarmonyAbi>
    <RuntimeIdentifier Condition="'$(OpenHarmonyAbi)' == 'x86_64'">linux-musl-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(OpenHarmonyAbi)' == 'arm64-v8a'">linux-musl-arm64</RuntimeIdentifier>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup Condition="'$(OpenHarmonyAbi)' == 'x86_64'">
    <PackageReference Include="OpenHarmony.NET.Runtime.NativeAot.x86_64" Version="10.0.10-ohos.2-preview.1" />
  </ItemGroup>
  <ItemGroup Condition="'$(OpenHarmonyAbi)' == 'arm64-v8a'">
    <PackageReference Include="OpenHarmony.NET.Runtime.NativeAot.arm64-v8a" Version="10.0.10-ohos.2-preview.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenHarmony.NET.PublishAotCross" Version="42.42.42-dev" />
  </ItemGroup>
</Project>
